// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqeX8SsN1Bpqro5-oFB6upsTpUowDRGm8',
    appId: '1:627639818770:web:35feab9d382cb5e25256cb',
    messagingSenderId: '627639818770',
    projectId: 'push-notification-e2888',
    authDomain: 'push-notification-e2888.firebaseapp.com',
    storageBucket: 'push-notification-e2888.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmFH9U2xkv9ubdlliLYazdW2VtUe6ZC6c',
    appId: '1:627639818770:android:91f3384995f8a60a5256cb',
    messagingSenderId: '627639818770',
    projectId: 'push-notification-e2888',
    storageBucket: 'push-notification-e2888.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjgGdnK942lZZ-O3QtAmPrmoZq9kLOnV0',
    appId: '1:627639818770:ios:c14befd355bcc6515256cb',
    messagingSenderId: '627639818770',
    projectId: 'push-notification-e2888',
    storageBucket: 'push-notification-e2888.firebasestorage.app',
    iosBundleId: 'com.example.ibmFlutterFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjgGdnK942lZZ-O3QtAmPrmoZq9kLOnV0',
    appId: '1:627639818770:ios:c14befd355bcc6515256cb',
    messagingSenderId: '627639818770',
    projectId: 'push-notification-e2888',
    storageBucket: 'push-notification-e2888.firebasestorage.app',
    iosBundleId: 'com.example.ibmFlutterFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqeX8SsN1Bpqro5-oFB6upsTpUowDRGm8',
    appId: '1:627639818770:web:b2bc8167923e3c875256cb',
    messagingSenderId: '627639818770',
    projectId: 'push-notification-e2888',
    authDomain: 'push-notification-e2888.firebaseapp.com',
    storageBucket: 'push-notification-e2888.firebasestorage.app',
  );
}
